version: '3'

networks:
  emag:

services:
  app:
    image: php:8.0-fpm-alpine
    tty: true
    volumes:
      - ./:/var/www/html/
    ports:
      - "9000"
    networks:
      - emag

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - emag